import "./globals.css";
import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import { ReactNode } from "react";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/theme-provider";
import Providers from "@/components/providers";
import { SessionProviderWrapper } from "@/components/Sessionproviderwrapper";

const arimo = Arimo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${arimo.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProviderWrapper>
            <Providers>{children}</Providers>
          </SessionProviderWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
