import "./globals.css";
import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import { ReactNode } from "react";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/theme-provider";
import Providers from "@/components/providers";
import { SessionProviderWrapper } from "@/components/Sessionproviderwrapper";

const inter = Inter_Tight({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider refetchOnWindowFocus={false} refetchInterval={0}>
            <SessionProviderWrapper>
              <Providers>{children}</Providers>
            </SessionProviderWrapper>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
